# -*- coding: utf-8 -*-
"""learn-beautiful-soup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPMFUI5y1thZaTltipj_JGOW2d1L7SdE
"""

import bs4
from bs4 import BeautifulSoup
import requests
import pandas as pd

# configure beautiful soup
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

# feed url into beautiful soup
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
page = requests.get(url, headers=headers)
bs = BeautifulSoup(page.text, 'html.parser')

# extract table, columns, and rows.
table0 = bs.find_all('table')[0]
columns = table0.find_all('th')
rows = table0.find_all('tr')

# create new pandas table, set columns, and fill rows.
df = pd.DataFrame(columns=[column.text.strip() for column in columns])
for row in rows[1:]:
  contents = [content.text.strip() for content in row.find_all('td')]
  current_index = len(df)
  df.loc[current_index] = contents

df
